new version, mssively cleaned deps, moved to python2.4
crashes at run-time:

/sw/lib/python2.4/site-packages/gtk-2.0/gnome/vfs.py:4: DeprecationWarning: Module gnome.vfs is deprecated; please import gnomevfs instead
  DeprecationWarning)
/sw/bin/gnome-blog-poster:31: GtkDeprecationWarning: gtk.FALSE is deprecated, use False instead
  if (value == None or value == gtk.FALSE):
Traceback (most recent call last):
  File "/sw/bin/gnome-blog-poster", line 51, in ?
    app = BloggerApp()
  File "/sw/bin/gnome-blog-poster", line 32, in __init__
    poster._showPrefDialog()
UnboundLocalError: local variable 'poster' referenced before assignment